name: Build

on:
  workflow_dispatch:
  # push:
  #   branches:
  # pull_request:

jobs:
  build:
    name: Build & Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - run: make
        working-directory: ./rust-ffi
      - run: ./main
        working-directory: ./rust-ffi
